In [1]:
import numpy as np

In [30]:
# Let's test some linear algebra tools starting with a randomly populated 100x3 array
X = np.random.random((100,3))
# Exercise: What is the shape of this?
X.shape
X.mean()

0.50027441190436739

In [47]:
# Covariance of centered data (X^T X)/sqrt(N-1)
Cx = np.dot(X.T, X)
Cx

array([[ 35.96483157,  25.05748924,  25.10384547],
       [ 25.05748924,  33.59270464,  23.12497812],
       [ 25.10384547,  23.12497812,  30.87445582]])

In [48]:
# Compute the singular value decomposition of the data matrix
# We can compute PCA through the eigenvalue decomposition of the covariance matrix (or SVD)
left_singular_vec, singular_vals, right_singular_vec = np.linalg.svd(X)
# Exercise: Use help menu and/or google to determine what these values are.
singular_vals**2

array([ 82.4480647 ,   9.84859006,   8.13533726])

In [49]:
# Get the eigenvalues and eigenvectors
eigval, eigvec = np.linalg.eigh(Cx)
print "eigenvectors"
print eigvec 
print " "
print "eigenvals", eigval

eigenvectors
[[-0.58863129  0.5344213  -0.60655345]
 [-0.14331872 -0.80741485 -0.57231199]
 [ 0.79559597  0.24995028 -0.55186222]]
 
eigenvals [  8.13533726   9.84859006  82.4480647 ]


In [12]:
# Exercise: Compare eigenvalues to singular values given the relationwhip between SVD
# and the covariance matrix.

PCA Exercise

In [13]:
from sklearn.decomposition import PCA

In [50]:
# Generate a 10-d array with 5 intrinsic dimensions
X3d = np.random.normal(size=(100,3))
R = np.random.random((3,10)) # Projection matrix
X10d = np.dot(X, R)

In [52]:
# Run pca
pca = PCA(n_components=5)
pca.fit(X10d)

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [53]:
# compute subspace
pca.transform(X10d)

array([[ -6.50639487e-01,  -3.59758642e-05,   2.73642717e-01,
          6.10622664e-16,  -1.11022302e-16],
       [ -4.72701123e-01,   2.80304315e-01,  -7.69216225e-02,
          5.96744876e-16,  -8.32667268e-17],
       [ -6.91492304e-01,   4.17444621e-01,  -8.59975099e-02,
          5.41233725e-16,   2.77555756e-17],
       [  1.12681267e+00,  -1.65332451e-01,   1.44284104e-01,
          4.57966998e-16,   2.22044605e-16],
       [  7.54732722e-01,  -2.99030000e-01,  -1.81849156e-01,
          4.71844785e-16,   5.55111512e-17],
       [ -1.75393778e-01,  -8.35526743e-01,   7.13200686e-03,
          5.41233725e-16,   0.00000000e+00],
       [ -7.25106009e-02,  -4.10312585e-01,  -3.43673033e-02,
          5.82867088e-16,  -6.93889390e-18],
       [  2.06625407e+00,   1.18073307e-01,  -1.92359425e-02,
          2.77555756e-16,   1.11022302e-16],
       [  1.55857594e+00,  -8.27373273e-02,   1.15343808e-01,
          5.27355937e-16,   1.11022302e-16],
       [ -9.74132328e-01,   2.9415857

In [54]:
# Mean of the data in 10-d
pca.mean_

array([ 0.83087302,  1.38350654,  0.66729281,  0.94355362,  0.98613301,
        0.35397908,  1.0655462 ,  0.51697066,  0.70182835,  0.86387658])

In [55]:
pca.explained_variance_
# Exercise: Explain the last value.

array([  7.40060837e-01,   1.48049436e-01,   1.73949154e-02,
         2.91573350e-31,   9.37998903e-33])

In [58]:
74+14.8+1.74

90.53999999999999