In [1]:
import numpy as np

In [13]:
# Let's test some linear algebra tools starting with a randomly populated 100x3 array
X = np.random.random((100,3))
# Exercise: What is the shape of this?

(100, 3)

In [3]:
# Covariance of centered data (X^T X)/sqrt(N-1)
Cx = np.dot(X.T, X)

In [43]:
# Compute the singular value decomposition of the data matrix
# We can compute PCA through the eigenvalue decomposition of the covariance matrix (or SVD)
left_singular_vec, singular_vals, right_singular_vec = np.linalg.svd(X)
# Exercise: Use help menu and/or google to determine what these values are.

In [38]:
# Get the eigenvalues and eigenvectors
eigval, eigvec = np.linalg.eigh(Cx)
print "eigenvectors"
print eigvec 
print " "
print "eigenvals", eigval

eigenvectors
[[-0.80393159  0.18435431 -0.56542682]
 [ 0.25371822 -0.75356632 -0.6064362 ]
 [ 0.53788574  0.6309923  -0.55904172]]
 
eigenvals [  7.47914231   8.5082569   90.05751791]


In [32]:
# Exercise: Compare eigenvalues to singular values given the relationwhip between SVD
# and the covariance matrix.

PCA Exercise

In [44]:
from sklearn.decomposition import PCA

In [49]:
# Generate a 10-d array with 5 intrinsic dimensions
X3d = np.random.normal(size=(100,3))
R = np.random.random((3,10)) # Projection matrix
X10d = np.dot(X, R)

In [51]:
# Run pca
pca = PCA(n_components=4)
pca.fit(X10d)

PCA(copy=True, n_components=4, whiten=False)

In [54]:
# compute subspace
pca.transform(X10d)

array([[ -9.83338737e-01,  -1.48877846e-01,  -2.43581338e-01,
          6.10622664e-16],
       [  1.19580216e-02,   1.10628902e-01,   3.40741223e-02,
          6.00214323e-16],
       [ -3.94507111e-01,  -1.12829366e-01,  -1.60304485e-02,
          6.45317133e-16],
       [ -5.16724198e-01,  -5.72050757e-02,  -8.30631914e-02,
          5.68989300e-16],
       [ -3.64948348e-01,  -1.80613824e-01,   7.11925223e-02,
          6.66133815e-16],
       [  2.30841396e-01,   2.36556789e-01,  -1.69264147e-02,
          8.70831185e-16],
       [  7.01194849e-01,  -1.05226005e-01,   5.38011262e-02,
          6.38378239e-16],
       [ -4.06528626e-01,  -1.22026316e-01,  -2.39373547e-01,
          6.69603262e-16],
       [ -6.17123225e-01,   1.04650658e-02,   1.32890383e-01,
          6.93889390e-16],
       [ -6.14086565e-01,   2.47732535e-01,   7.67892867e-02,
          7.28583860e-16],
       [ -1.72198650e+00,   2.51418898e-02,  -6.74835450e-02,
          5.82867088e-16],
       [  1.03556001e

In [57]:
# Mean of the data in 10-d
pca.mean_

array([ 0.88950679,  0.97257951,  0.8978474 ,  0.88506342,  1.52245737,
        1.24926385,  0.96266548,  0.69525105,  0.41248555,  0.85924934])

In [58]:
pca.explained_variance_
# Exercise: Explain the last value.

array([  8.68396509e-01,   1.83337506e-02,   1.16892927e-02,
         4.71001729e-31])